// src/config.js

export const CONFIG = {
    SAVE_KEY: 'chickenClickerSave_v3.4',
    GAME_VERSION: '3.5 (The Lunar Rescue)',
    GAME_TICK_INTERVAL: 0.1,
    SAVE_INTERVAL: 5,
    GOLDEN_CHICKEN_SPAWN_INTERVAL: 60,
    RANDOM_EVENT_INTERVAL: 180,
    INTERACTIVE_EVENT_INTERVAL: 120,
    COLORED_EGG_ATTEMPT_INTERVAL: 15,
    COLORED_EGG_SPAWN_CHANCE: 10 / 240,
    ARTIFACT_DIG_CHANCE: 0.0005, // Reduced to 0.05% (1 in 2,000 clicks)
    PRESTIGE_COST: 1e12,
    DARK_MATTER_PER_CLICK: 2, // Base Dark Matter per click
    ARTIFACTS: {
        ancientKernel: { 
            name: "Ancient Kernel", 
            desc: "Petrified corn. Hard as a rock.", 
            bonusDesc: "+1% Click Power", 
            effect: 'click', 
            value: 0.01,
            svg: '<ellipse cx="50" cy="50" rx="30" ry="40" fill="#e67e22" /><circle cx="40" cy="40" r="5" fill="#d35400" /><circle cx="60" cy="60" r="5" fill="#d35400" /><circle cx="60" cy="30" r="5" fill="#d35400" />'
        },
        rustySpur: { 
            name: "Rusty Spur", 
            desc: "From a cowboy who rode a rooster?", 
            bonusDesc: "+1% EPS", 
            effect: 'eps', 
            value: 0.01,
            svg: '<path d="M20,20 Q50,80 80,20" fill="none" stroke="#8d6e63" stroke-width="10" /><circle cx="50" cy="80" r="10" fill="#8d6e63" /><circle cx="50" cy="80" r="4" fill="#fff" />' 
        },
        goldenFeatherFossil: { 
            name: "Feather Fossil", 
            desc: "Evidence of early evolution.", 
            bonusDesc: "+5% Feather Chance", 
            effect: 'feather', 
            value: 0.05,
            svg: '<rect x="20" y="20" width="60" height="60" fill="#95a5a6" rx="5" /><path d="M50,30 Q60,50 50,70" stroke="#7f8c8d" stroke-width="2" fill="none" /><path d="M50,35 L60,40 M50,45 L60,50 M50,55 L60,60" stroke="#7f8c8d" stroke-width="2" />'
        },
        moonRockSample: { 
            name: "Moon Rock", 
            desc: "How did this get here?", 
            bonusDesc: "+10% Prestige Gain", 
            effect: 'prestige', 
            value: 0.1,
            svg: '<path d="M30,70 L40,30 L70,20 L80,60 L60,80 Z" fill="#546e7a" /><circle cx="45" cy="40" r="3" fill="#37474f" /><circle cx="65" cy="65" r="5" fill="#37474f" />'
        },
        firstEgg: { 
            name: "The First Egg", 
            desc: "Which came first? This one.", 
            bonusDesc: "+5% Global Multiplier", 
            effect: 'global', 
            value: 0.05,
            svg: '<ellipse cx="50" cy="50" rx="30" ry="40" fill="#f5f5dc" stroke="#dcd0c0" stroke-width="2"/><path d="M40,30 L50,40 L60,30" fill="none" stroke="#dcd0c0" stroke-width="2"/>'
        },
        oldBoot: { 
            name: "Old Boot", 
            desc: "Useless. Smells faintly of cheese.", 
            bonusDesc: "No bonus.", 
            effect: 'none', 
            value: 0,
            svg: '<path d="M30,20 L30,60 L60,60 L70,70 L80,60 L80,20 Z" fill="#5d4037" /><rect x="30" y="60" width="30" height="10" fill="#3e2723" />'
        },
        donatorPack: {
            name: "Donator Pack",
            desc: "A mysterious box left by a generous benefactor.",
            bonusDesc: "???",
            effect: 'none', // Handled specially
            value: 0,
            svg: '<rect x="10" y="40" width="80" height="40" fill="#e74c3c" stroke="#c0392b" stroke-width="2"/><rect x="45" y="40" width="10" height="40" fill="#f1c40f"/><rect x="10" y="30" width="80" height="10" fill="#c0392b"/><path d="M40,30 L40,15 Q20,10 45,30 M60,30 L60,15 Q80,10 55,30" fill="#f1c40f" stroke="#f39c12" stroke-width="2"/>'
        }
    },
    SKINS: {
        default: { name: "Default Chicken", desc: "The classic clucker. No frills.", svg: `<rect x="30" y="40" width="40" height="40" fill="white" /><rect x="30" y="30" width="20" height="10" fill="white" /><rect x="70" y="40" width="10" height="10" fill="orange" /><rect x="30" y="20" width="10" height="10" fill="red" /><rect x="40" y="80" width="5" height="15" fill="orange" /><rect x="55" y="80" width="5" height="15" fill="orange" /><rect x="50" y="35" width="5" height="5" fill="black" />`},
        leghorn: { name: "Leghorn Look", desc: "A sleek, no-nonsense classic white.", svg: `<rect x="30" y="40" width="40" height="40" fill="lightgray" /><rect x="30" y="30" width="20" height="10" fill="lightgray" /><rect x="70" y="40" width="10" height="10" fill="orange" /><rect x="30" y="20" width="10" height="10" fill="red" /><rect x="40" y="80" width="5" height="15" fill="orange" /><rect x="55" y="80" width="5" height="15" fill="orange" /><rect x="50" y="35" width="5" height="5" fill="black" />`},
        silkie: { name: "Silkie Style", desc: "Fluffy and fabulous.", svg: `<circle cx="50" cy="50" r="30" fill="white" /><circle cx="40" cy="30" r="10" fill="white" /><circle cx="60" cy="30" r="10" fill="white" /><rect x="70" y="40" width="10" height="10" fill="orange" /><circle cx="50" cy="20" r="5" fill="red" /><rect x="40" y="80" width="5" height="15" fill="orange" /><rect x="55" y="80" width="5" height="15" fill="orange" /><circle cx="50" cy="35" r="3" fill="black" />`},
        rooster: { name: "Rooster Royalty", desc: "Proud and vibrant.", svg: `<rect x="30" y="40" width="40" height="40" fill="darkred" /><rect x="30" y="30" width="20" height="10" fill="darkred" /><rect x="70" y="40" width="10" height="10" fill="orange" /><path d="M30,20 L35,15 L40,20 L35,25 Z" fill="yellow" /><rect x="40" y="80" width="5" height="15" fill="orange" /><rect x="55" y="80" width="5" height="15" fill="orange" /><rect x="50" y="35" width="5" height="5" fill="black" />`},
        quantum: { name: "Quantum Form", desc: "A glitch in the matrix. Pixelated and electric.", svg: `<rect x="30" y="40" width="40" height="40" fill="cyan" /><rect x="30" y="30" width="20" height="10" fill="cyan" /><rect x="70" y="40" width="10" height="10" fill="lightgreen" /><rect x="30" y="20" width="10" height="10" fill="blue" /><rect x="40" y="80" width="5" height="15" fill="lightgreen" /><rect x="55" y="80" width="5" height="15" fill="lightgreen" /><rect x="50" y="35" width="5" height="5" fill="white" />`},
        astronaut: { name: "Astro-Chicken", desc: "One small peck for chicken-kind.", svg: `<rect x="30" y="40" width="40" height="40" fill="#e0e0e0" stroke="#999" stroke-width="2" /><rect x="30" y="30" width="20" height="10" fill="#e0e0e0" /><rect x="70" y="40" width="10" height="10" fill="orange" /><rect x="40" y="80" width="5" height="15" fill="orange" /><rect x="55" y="80" width="5" height="15" fill="orange" /><circle cx="45" cy="30" r="18" fill="rgba(100, 200, 255, 0.4)" stroke="#aaa" stroke-width="2" /><rect x="50" y="35" width="5" height="5" fill="black" />`},
    },
    UPGRADES: {
        shovel: { name: 'Archaeologist\'s Shovel', desc: 'Allows you to dig for ancient artifacts while clicking.', baseCost: 10000, exponent: 1000, currency: 'eggs', color: 'brown', oneTime: true }, // High exponent to ensure max level 1 basically
        worker: { name: 'Coop Worker', desc: 'Each level helps Leghorn Chickens produce +1 EPS.', baseCost: 10, exponent: 1.15, currency: 'eggs', color: 'green' },
        incubator: { name: 'Incubator', desc: 'Each level increases your base Eggs Per Click by +1.', baseCost: 50, exponent: 1.15, currency: 'eggs', color: 'blue' },
        loom: { name: 'Golden Loom', desc: 'Uses Golden Feathers to boost eggs per click by +25% per level.', baseCost: 10, exponent: 1.5, currency: 'feathers', color: 'yellow' },
        featherForecast: { name: 'Feather Forecast', desc: 'Increases Golden Feather find chance.', baseCost: 10000, exponent: 1.8, currency: 'eggs', color: 'gray' },
        eggstraClicks: { name: 'Eggstra Clicks', desc: 'Each click has a chance to be 10x stronger.', baseCost: 50000, exponent: 1.25, currency: 'eggs', color: 'pink' },
        cluckworkAutomation: { name: 'Cluckwork Automation', desc: 'Boosts EPS by 5% for every building owned.', baseCost: 1e6, exponent: 2, currency: 'eggs', color: 'purple' },
        peckingOrder: { name: 'Pecking Order', desc: 'A flat +10% boost to both clicks and EPS.', baseCost: 1e7, exponent: 1.5, currency: 'eggs', color: 'indigo' },
        nestEggIRA: { name: 'Nest Egg IRA', desc: 'Earn 0.1% of your base EPS as interest per second (capped).', baseCost: 1e9, exponent: 2.5, currency: 'eggs', color: 'teal' },
        fowlLanguage: { name: 'Fowl Language', desc: 'The chicken occasionally squawks insults. Essential.', baseCost: 1e12, exponent: 10, currency: 'eggs', color: 'red' },
        goldenCompass: { name: 'Golden Compass', desc: 'Increases the egg bonus from Golden Chickens by 25% per level.', baseCost: 25, exponent: 1.6, currency: 'feathers', color: 'yellow' },
        comfyCoopBedding: { name: 'Comfy Coop Bedding', desc: 'Increases the maximum offline progress time by 2 hours per level.', baseCost: 5e12, exponent: 2.2, currency: 'eggs', color: 'teal' },
        prismaticFeed: { name: 'Prismatic Feed', desc: 'Increases the duration of all Colored Egg buffs by 10% per level.', baseCost: 1e15, exponent: 2.5, currency: 'eggs', color: 'pink' },
        spaceProgram: { name: 'Space Program', desc: 'Unlocks the ability to travel to the Moon.', baseCost: 1e9, exponent: 1, currency: 'eggs', color: 'black' },
        quantumEggTheory: { name: 'Quantum Egg Theory', desc: 'Understand the physics of egg-laying. Quantum Cluckers are 50% more effective.', baseCost: 1e42, exponent: 4, currency: 'eggs', color: 'cyan' },
        eventHorizon: { name: 'Event Horizon', desc: 'Compresses time. +2% EPS for every Prestige level you have.', baseCost: 1e45, exponent: 3, currency: 'eggs', color: 'black' }
    },
    CHICKENS: {
        leghorn: { name: 'Leghorn Chicken', desc: 'The backbone of your coop. Produces 1 egg/s per Coop Worker.', baseCost: 1000, exponent: 1.25, color: 'gray' },
        silkie: { name: 'Silkie Chicken', desc: 'Produces fewer eggs but has a chance to find Golden Feathers.', baseCost: 5000, exponent: 1.25, color: 'orange' },
        rooster: { name: 'Rooster', desc: 'Doesn\'t lay eggs. Grants a base of 1,000 Reputation on prestige instead.', baseCost: 1e6, exponent: 1.25, color: 'red', repValue: 1000 },
        orpington: { name: 'Orpington Oracle', desc: 'Grants a random egg bonus every 10 minutes.', baseCost: 1e8, exponent: 1.3, color: 'yellow' },
        wyandotte: { name: 'Wyandotte Warrior', desc: 'Increases Reputation gained on prestige by 5% per chicken.', baseCost: 1e10, exponent: 1.35, color: 'blue' },
        doja: { name: 'Doja Cow', desc: '"Moooove over!" Each click has a chance to be a "Super Click", granting 1 hour of EPS. Landing Super Clicks within 10 seconds of each other creates a chain, increasing the bonus by 10% each time!', baseCost: 5e12, exponent: 1.4, color: 'pink' },
        brahma: { name: 'Brahma Behemoth', desc: 'A gentle giant. Adds a massive +500% to your base EPS.', baseCost: 1e15, exponent: 1.45, color: 'green' },
        serama: { name: 'Serama Sorcerer', desc: 'Has a chance to grant a free upgrade level.', baseCost: 1e18, exponent: 1.5, color: 'purple' },
        banty: { name: 'Banty Chicken', desc: 'The king. Provides a +10% multiplicative bonus to ALL production.', baseCost: 1e21, exponent: 1.6, color: 'indigo' },
        quantum: { name: 'Quantum Clucker', desc: 'Exists in multiple coops at once. Multiplies EPS by (1 + Unlocked Achievements).', baseCost: 1e40, exponent: 1.8, color: 'cyan' },
        voidChicken: { name: 'Void Chicken', desc: 'Stares back. Consumes reality to produce eggs.', baseCost: 1e54, exponent: 2.0, color: 'black' }
    },
    LUNAR_UPGRADES: { // New section for lunar upgrades
        moonMiner: { name: 'Moon Miner', desc: 'Extracts Dark Matter from lunar soil. +1 DM/s per level.', baseCost: 100, exponent: 1.2, currency: 'moonEggs', color: 'gray' },
        gravStabilizer: { name: 'Gravity Stabilizer', desc: 'Reduces lunar gravity. +1 DM/click per level.', baseCost: 500, exponent: 1.2, currency: 'moonEggs', color: 'white' },
        cosmicDustFilter: { name: 'Cosmic Dust Filter', desc: 'Increases Moon Egg production efficiency. +10% Moon Eggs per level.', baseCost: 10000, exponent: 1.3, currency: 'darkMatter', color: 'purple' },
        temporalAccelerator: { name: 'Temporal Accelerator', desc: 'Uses Dark Matter to speed up Earth time. +5% Global EPS per level.', baseCost: 250, exponent: 1.5, currency: 'darkMatter', color: 'blue' }
    },
    LUNAR_CHICKENS: { // New section for lunar chickens
        lunar: { name: 'Lunar Hen', desc: 'A sturdy chicken adapted to lunar life. Produces 1 Moon Egg/s per Moon Miner.', baseCost: 1000, exponent: 1.3, currency: 'darkMatter', color: 'silver' },
        alien: { name: 'Alien Clucker', desc: 'Mysterious origins. Generates Dark Matter over time.', baseCost: 1e6, exponent: 1.4, color: 'lime' }
    },
    COLORED_EGGS: {
        green:  { likelihood: 15, effect: 'discount', value: 0.1, duration: 5, color: '#4ade80' },
        red:    { likelihood: 15, effect: 'clickFrenzy', value: 5, duration: 30, color: '#f87171' },
        pink:   { likelihood: 14, effect: 'instantGain', value: 1800, duration: 0, color: '#f472b6' },
        orange: { likelihood: 14, effect: 'featherFrenzy', value: 2, duration: 600, color: '#fb923c' },
        yellow: { likelihood: 13, effect: 'goldRush', value: 3, duration: 0, color: '#facc15' },
        white:  { likelihood: 10, effect: 'boostMultiplier', value: 2, duration: 60, color: '#f9fafb' },
        black:  { likelihood: 6,  effect: 'superClickFrenzy', value: 2, duration: 60, color: '#1f2937' },
        blue:   { likelihood: 6,  effect: 'prestigeBuff', value: 0.1, duration: -1, color: '#60a5fa' },
        purple: { likelihood: 3,  effect: 'prestigePercent', value: 0.01, duration: 0, color: '#a78bfa' },
        gold:   { likelihood: 1,  effect: 'permanentBonus', value: 0.01, duration: -1, color: 'gold' }
    }
};

export const FOWL_INSULTS = [
    "Peck off!",
    "Cluck you!",
    "Is that all you've got?",
    "My grandmother clicks harder.",
    "You call that a click?",
    "Bawk-bawk-BUM!",
    "Don't ruffle my feathers.",
];

export const achievements = {
    bantySecret: { name: "Banty 4 Life", description: "Unlocked via secret password. Share a screenshot with the dev!", bonus: 1.25, hidden: true },
    bigFind: { name: "The Big Find", description: "You found the Donator Pack! Contact the dev!", bonus: 5.0, hidden: true }, // New Achievement
    click1: { name: "First Peck", description: "Click the chicken once.", bonus: 1.01 },
    click1k: { name: "Click Addict", description: "Click 1,000 times.", bonus: 1.02 },
    click100k: { name: "Carpal Tunnel Hopeful", description: "Click 100,000 times.", bonus: 1.05 },
    click1M: { name: "Million-Click March", description: "Click 1,000,000 times.", bonus: 1.1 },
    egg1k: { name: "First Dozen", description: "Earn 1,000 total eggs.", bonus: 1.01 },
    egg1M: { name: "Egg Millionaire", description: "Earn 1,000,000 total eggs.", bonus: 1.03 },
    egg1B: { name: "Egg Billionaire", description: "Earn 1,000,000,000 total eggs.", bonus: 1.05 },
    egg1T: { name: "Trillionaire's Omelette", description: "Earn 1 Trillion total eggs.", bonus: 1.1 },
    worker25: { name: "Coop Manager", description: "Own 25 Coop Workers.", bonus: 1.02 },
    worker100: { name: "Foreman of the Flock", description: "Own 100 Coop Workers.", bonus: 1.05 },
    incubator25: { name: "Industrial Revolution", description: "Own 25 Incubators.", bonus: 1.02 },
    incubator100: { name: "Clickpocalypse", description: "Own 100 Incubators.", bonus: 1.05 },
    loom1: { name: "Golden Threads", description: "Build your first Golden Loom.", bonus: 1.05 },
    loom10: { name: "Rich Tapestry", description: "Own 10 Golden Looms.", bonus: 1.1 },
    featherForecast1: { name: "Good Omen", description: "Buy a Feather Forecast.", bonus: 1.02 },
    eggstraClicks1: { name: "Lucky Break", description: "Buy an Eggstra Clicks.", bonus: 1.02 },
    cluckworkAutomation1: { name: "Synergy", description: "Buy Cluckwork Automation.", bonus: 1.03 },
    peckingOrder1: { name: "Top of the Order", description: "Buy a Pecking Order.", bonus: 1.03 },
    nestEggIRA1: { name: "Retirement Plan", description: "Start a Nest Egg IRA.", bonus: 1.05 },
    fowlLanguage1: { name: "Why I Oughta!", description: "Buy Fowl Language.", bonus: 1.01 },
    silkie1: { name: "Fluffy", description: "Buy your first Silkie Chicken.", bonus: 1.02 },
    rooster1: { name: "Cocky", description: "Buy your first Rooster.", bonus: 1.02 },
    orpington1: { name: "Fortune Teller", description: "Buy an Orpington Oracle.", bonus: 1.03 },
    wyandotte1: { name: "Reputable", description: "Buy a Wyandotte Warrior.", bonus: 1.03 },
    doja1: { name: "Moooove Over", description: "Buy a Doja Cow.", bonus: 1.05 },
    brahma1: { name: "Gentle Giant", description: "Buy a Brahma Behemoth.", bonus: 1.05 },
    serama1: { name: "Freebie!", description: "Buy a Serama Sorcerer.", bonus: 1.07 },
    banty1: { name: "King of the Coop", description: "Buy the legendary Banty Chicken.", bonus: 1.1 },
    secondChance: { name: "Second Chance", description: "Prestige for the first time.", bonus: 1.10 },
    eternalFarmer: { name: "Eternal Farmer", description: "Prestige 10 times.", bonus: 1.25 },
    prestigeWorldwide: { name: "Prestige Worldwide", description: "Prestige 25 times.", bonus: 1.5 },
    goldenTouch: { name: "Golden Touch", description: "Click your first Golden Chicken.", bonus: 1.02 },
    goldRush: { name: "Gold Rush", description: "Click 10 Golden Chickens.", bonus: 1.10 },
    goldFever: { name: "Gold Fever", description: "Click 50 Golden Chickens.", bonus: 1.2 },
    eggGreen: { name: "Going Green", description: "Find a Green Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggRed: { name: "Seeing Red", description: "Find a Red Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggPink: { name: "In the Pink", description: "Find a Pink Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggOrange: { name: "Orange You Glad", description: "Find an Orange Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggYellow: { name: "Mellow Yellow", description: "Find a Yellow Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggWhite: { name: "Plain and Simple", description: "Find a White Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggBlack: { name: "Back in Black", description: "Find a Black Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggBlue: { name: "Feeling Blue", description: "Find a Blue Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggPurple: { name: "Purple Reign", description: "Find a Purple Egg.", bonus: 1.01, hidden: true, noToast: true },
    eggGold: { name: "Midas Touch", description: "Find a Gold Egg.", bonus: 1.05, hidden: true, noToast: true },
    impatient: { name: "Impatient", description: "Try to buy something you can't afford 50 times.", bonus: 1.01, hidden: true },
    license: { name: "License and Registration", description: "Read the license.", bonus: 1.01, hidden: true },
    reset: { name: "What Did It Do To You?", description: "Use the Hard Reset button.", bonus: 1.00, hidden: true },
    lazy: { name: "Are You Even Trying?", description: "Don't click the chicken for the first 2 minutes.", bonus: 1.05, hidden: true },
    loner: { name: "Just Me and My Chicken", description: "Reach 1M eggs without buying any Coop Workers.", bonus: 1.10, hidden: true },
    afk: { name: "Still There?", description: "Don't click anything for 15 minutes.", bonus: 1.1, hidden: true },
    indecisive: { name: "Window Shopper", description: "Open and close a modal 50 times.", bonus: 1.02, hidden: true },
    justTheBasics: { name: "Old School", description: "Reach 10M eggs using only Leghorn Chickens.", bonus: 1.15, hidden: true },
    allUpgrades: { name: "Master Builder", description: "Buy at least one of every upgrade.", bonus: 1.2, hidden: true },
    allChickens: { name: "Gotta Cluck 'Em All", description: "Own at least one of every chicken.", bonus: 1.2, hidden: true },
    eggCollector: { name: "Taste the Rainbow", description: "Find one of every colored egg.", bonus: 1.25, hidden: true },
    firstInsult: { name: "Ruffled Feathers", description: "Witness the chicken's dark side for the first time.", bonus: 1.01, hidden: true },
    eagle1: { name: "Bird Watcher", description: "Scare away an Eagle.", bonus: 1.01 },
    eagle10: { name: "No Fly Zone", description: "Scare away 10 Eagles.", bonus: 1.02 },
    eagle50: { name: "Apex Predator", description: "Scare away 50 Eagles. They fear you now.", bonus: 1.05 },
    fox1: { name: "What Does It Say?", description: "Catch a Fox lurking in the bushes.", bonus: 1.01 },
    badger1: { name: "Mushroom Mushroom!", description: "Tickle a Badger. Snake not included.", bonus: 1.05, hidden: true },
    umbrella1: { name: "Drying Off", description: "Use an Umbrella during a storm.", bonus: 1.01 },
    umbrella10: { name: "Kingsman", description: "Manners maketh man. Use 10 Umbrellas.", bonus: 1.03 },
};

export const achievementConditions = {
    bantySecret: (gs) => false, // Manual unlock
    bigFind: (gs) => gs.artifacts.includes('donatorPack'), // New condition
    click1: (gs) => gs.totalClicks >= 1, click1k: (gs) => gs.totalClicks >= 1000, click100k: (gs) => gs.totalClicks >= 100000, click1M: (gs) => gs.totalClicks >= 1e6,
    egg1k: (gs) => gs.totalEggs >= 1000, egg1M: (gs) => gs.totalEggs >= 1e6, egg1B: (gs) => gs.totalEggs >= 1e9, egg1T: (gs) => gs.totalEggs >= 1e12,
    worker25: (gs) => gs.upgrades.worker >= 25, worker100: (gs) => gs.upgrades.worker >= 100,
    incubator25: (gs) => gs.upgrades.incubator >= 25, incubator100: (gs) => gs.upgrades.incubator >= 100,
    loom1: (gs) => gs.upgrades.loom >= 1, loom10: (gs) => gs.upgrades.loom >= 10,
    featherForecast1: (gs) => gs.upgrades.featherForecast >= 1, eggstraClicks1: (gs) => gs.upgrades.eggstraClicks >= 1,
    cluckworkAutomation1: (gs) => gs.upgrades.cluckworkAutomation >= 1, peckingOrder1: (gs) => gs.upgrades.peckingOrder >= 1,
    nestEggIRA1: (gs) => gs.upgrades.nestEggIRA >= 1, fowlLanguage1: (gs) => gs.upgrades.fowlLanguage >= 1,
    silkie1: (gs) => gs.chickens.silkie >= 1, rooster1: (gs) => gs.chickens.rooster >= 1,
    orpington1: (gs) => gs.chickens.orpington >= 1, wyandotte1: (gs) => gs.chickens.wyandotte >= 1,
    doja1: (gs) => gs.chickens.doja >= 1, brahma1: (gs) => gs.chickens.brahma >= 1,
    serama1: (gs) => gs.chickens.serama >= 1, banty1: (gs) => gs.chickens.banty >= 1,
    secondChance: (gs) => gs.prestigeCount >= 1, eternalFarmer: (gs) => gs.prestigeCount >= 10, prestigeWorldwide: (gs) => gs.prestigeCount >= 25,
    goldenTouch: (gs) => gs.goldenChickensClicked >= 1, goldRush: (gs) => gs.goldenChickensClicked >= 10, goldFever: (gs) => gs.goldenChickensClicked >= 50,
    eggGreen: (gs) => gs.clickedColoredEggs['green'], eggRed: (gs) => gs.clickedColoredEggs['red'], eggPink: (gs) => gs.clickedColoredEggs['pink'],
    eggOrange: (gs) => gs.clickedColoredEggs['orange'], eggYellow: (gs) => gs.clickedColoredEggs['yellow'], eggWhite: (gs) => gs.clickedColoredEggs['white'],
    eggBlack: (gs) => gs.clickedColoredEggs['black'], eggBlue: (gs) => gs.clickedColoredEggs['blue'], eggPurple: (gs) => gs.clickedColoredEggs['purple'],
    eggGold: (gs) => gs.clickedColoredEggs['gold'],
    impatient: (gs) => gs.failedBuys >= 50, license: (gs) => gs.licenseClicked, reset: (gs) => gs.resets > 0,
    lazy: (gs) => gs.totalClicks === 0 && gs.timePlayed >= 120,
    loner: (gs) => gs.totalEggs >= 1e6 && gs.upgrades.worker === 0,
    afk: (gs) => gs.timeSinceLastClick >= 900,
    indecisive: (gs) => gs.modalOpens >= 50,
    justTheBasics: (gs) => gs.totalEggs >= 1e7 && Object.keys(gs.chickens).every(c => c === 'leghorn' || gs.chickens[c] === 0),
    allUpgrades: (gs) => Object.keys(CONFIG.UPGRADES).every(u => gs.upgrades[u] > 0),
    allChickens: (gs) => Object.keys(CONFIG.CHICKENS).every(c => gs.chickens[c] > 0),
    eggCollector: (gs) => Object.keys(CONFIG.COLORED_EGGS).every(c => gs.clickedColoredEggs[c]),
    firstInsult: (gs) => gs.firstInsultFired,
    eagle1: (gs) => gs.eagleClicks >= 1, eagle10: (gs) => gs.eagleClicks >= 10, eagle50: (gs) => gs.eagleClicks >= 50,
    fox1: (gs) => gs.foxClicks >= 1, badger1: (gs) => gs.badgerClicks >= 1,
    umbrella1: (gs) => gs.umbrellaClicks >= 1, umbrella10: (gs) => gs.umbrellaClicks >= 10,
};
